Review #1
aleoreh/stellar-burger pull request #1
Opened 2024-05-30 13:33 UTC by aleoreh

Сдача проектной работы "Redux-хранилище "Stellar Burger"

2024-05-30 16:09 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- На будущее, никогда не храните заполненные (любые) `.env` файлы в гите, это не безопасно. Всегда добавляйте такие файлы в `.gitignore`;

- У вас идёт бесконечная загрузка на страницах `/profile/orders/:id`;

- Нужно поправить иконки в хедере, иконка должна быть белой, только у активной ссылки. <https://disk.yandex.com/i/Pjcugu676iXfyQ>;

- <https://disk.yandex.com/i/qR0kJ4LrXq0_ag> - надо поправить поведение роутинга, при открытии модального окна `/feed/:id` и `/profile/orders/:id`;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-05-30 16:09 UTC, ArslanMustafin commented on src/components/app/app.tsx
> +    dispatch(getFeeds());
**Надо исправить:**

Здесь и далее.

не стоит вызывать все запросы в app, пользователь может быть вообще не зайдёт на другие страницы, а лишние запросы, это практически всегда не очень хорошо))  В данном случае `getFeeds` и `getUserOrders` нужно вызывать на своих страницах, а не в компоненте app.

2024-05-30 16:09 UTC, ArslanMustafin commented on src/components/ui/burger-constructor/burger-constructor.tsx
> +        disabled={!(isReady || isReady === undefined)}
**Можно лучше:**

не совсем понимаю, зачем тут доп условие `isReady === undefined`. `!isReady` - по умолчанию же будет тру, если значение  `undefined`

2024-05-30 16:09 UTC, ArslanMustafin commented on src/services/slices/orderSlice.ts
> +        { ...action.payload, id: generateId(state.ingredients) }
**Надо исправить:**

Редьюсеры — чистые функции, в них не должно быть генерации каких-нибудь айдишников.
Для этого есть prepare. <https://redux-toolkit.js.org/api/createslice#customizing-generated-action-creators>

2024-05-30 16:09 UTC, ArslanMustafin commented on src/utils/remote-data.ts
> +    defaultError: string | null | undefined
**Можно лучше:**

Лучше придерживаться единого  стиля написания кода, лучше вынести в отдельные функции, как вы сделали это выше))

2024-05-30 17:32 UTC, aleoreh commented on src/services/slices/orderSlice.ts
> +        { ...action.payload, id: generateId(state.ingredients) }
Последний id будет храниться в state и при добавлении строки будет применён инкремент и сохранён в state

2024-05-30 20:08 UTC, aleoreh commented on src/services/slices/orderSlice.ts
> +        { ...action.payload, id: generateId(state.ingredients) }
`generateId` была чистой - зависела только от `state.ingredients`

2024-05-31 05:01 UTC, aleoreh commented
Файл `.env.example` пришёл вместе с проектом, поэтому я не стал его трогать.
Чтобы его удалить, придётся менять всю историю. Можно попробовать сделать только после закрытия PR

2024-05-31 05:21 UTC, aleoreh commented
"бесконечная загрузка на страницах /profile/orders/:id"
Я так понял, что на некоторых заказах всё время крутился спиннер, если их не было в хранилище.
Исправлено. Данные теперь получаются с сервера при открытии окна.

2024-05-31 05:22 UTC, aleoreh commented
"иконка должна быть белой, только у активной ссылки"
Исправлено

2024-05-31 05:24 UTC, aleoreh commented
"поведение роутинга, при открытии модального окна /feed/:id и /profile/orders/:id"
При открытии модального окна в бэкграунд выводился компонент по маршруту `/`
Исправлено

2024-05-31 05:34 UTC, aleoreh commented on src/components/order-info/order-info.tsx
> +    getOrderByNumberApi(number).then((res) => {
Намеренно не стал подключать для этого `store`, потому что не смог представить, зачем нужно там хранить последнюю полученную информацию о заказе

2024-05-31 08:21 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает приложение лучше:**

- <https://disk.yandex.com/i/X7RmI8ENniF8oA> - нужно поправить `z-index` у элементов), либо увеличить у модального окна;

2024-05-31 08:22 UTC, ArslanMustafin commented
> Файл `.env.example` пришёл вместе с проектом, поэтому я не стал его трогать. Чтобы его удалить, придётся менять всю историю. Можно попробовать сделать только после закрытия PR

Это понятно)) поэтому я и написал "на будущее")

2024-05-31 08:31 UTC, merged